# -*- coding: utf-8 -*-
"""titanicfrocompetition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug3PxykEjw8fFs2FmM0yt2ws6-RL9e53
"""

import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import matplotlib.pyplot as plt

import plotly
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('titanic_dataset.csv')

df.head()

df.tail()

df.sample()

df.isna().sum()

df.describe()

df.info()

df.corr(numeric_only=True)

# sns.scatterplot(x = df['Embarked'],y = df['Pclass'],hue=df['Survived'],palette='rainbow')

df.sample()

df.shape

df1 = df.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis=1)

df1.head()

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

X_train,X_test,y_train,y_test = train_test_split(df1,df['Survived'],test_size=0.2,random_state=42)

X_train.head()

X_train.shape

X_test.shape

y_train.head()

y_train.shape

y_test.shape

# Define feature types (matching carpriceprediction.py structure)
categorical_features = ['Sex', 'Embarked']
numeric_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), categorical_features),
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), numeric_features)
    ]
)

pipe = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', LogisticRegression())
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

y_pred

accuracy_score(y_test,y_pred)

df2 = pd.read_csv('test.csv')

df2.sample()

passenger_ids = df2['PassengerId']

df2.drop(['PassengerId','Name','Cabin','Ticket'],axis=1,inplace=True)

df2.head()

df2.isna().sum()

y2_pred = pipe.predict(df2)

y2_pred

from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipe, X_train, y_train, cv=5)

scores



X_train.to_csv('X_train_cleaned.csv', index=False)
y_train.to_csv('y_train_cleaned.csv', index=False)
X_test.to_csv('X_test_cleaned.csv', index=False)
y_test.to_csv('y_test_cleaned.csv', index=False)

print('Saved X_train_cleaned.csv, y_train_cleaned.csv, X_test_cleaned.csv, y_test_cleaned.csv')



# pip install shap lime

import shap
import lime
import lime.lime_tabular

# Extract the preprocessor and model from the pipeline
preprocessor = pipe.named_steps['preprocessing']
model = pipe.named_steps['model']

# Fit preprocessor to get feature names
preprocessor.fit(X_train)

# Get feature names after preprocessing
cat_ohe = preprocessor.named_transformers_['cat'].named_steps['onehot']
cat_feature_names = cat_ohe.get_feature_names_out(categorical_features)
num_feature_names = numeric_features  # StandardScaler preserves feature names

feature_names = list(cat_feature_names) + list(num_feature_names)


# Transform X_train for SHAP and LIME
X_train_transformed = preprocessor.transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

"""### SHAP Explanations

"""

# SHAP Explainer
explainer = shap.Explainer(model, X_train_transformed, feature_names=feature_names)
shap_values = explainer(X_test_transformed)

# SHAP Summary Plot (Beeswarm)
shap.summary_plot(shap_values, X_test_transformed, feature_names=feature_names)

"""### LIME Explanations

"""

# LIME Explainer
# The predict_proba_fn must now take already transformed data,
# as the lime_explainer itself is initialized with transformed data.
def predict_proba_fn(X_transformed_data):
    return model.predict_proba(X_transformed_data)

# The training_data for LimeTabularExplainer is already numerical (X_train_transformed).
# All features in X_train_transformed are numerical, so LIME will treat them as such.
# The feature_names list corresponds to the columns in X_train_transformed.


lime_explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train_transformed,
    feature_names=feature_names,
    class_names=['Not Survived', 'Survived'],
    mode='classification',
    random_state=42 # for reproducibility
)

# Explain a few instances from X_test
# Now, pass the *transformed* test instance to explain_instance.
print("\nLIME Explanation for X_test instance 0:")
exp = lime_explainer.explain_instance(X_test_transformed[0], predict_proba_fn, num_features=5)
exp.show_in_notebook(show_table=True)

print("\nLIME Explanation for X_test instance 1:")
exp = lime_explainer.explain_instance(X_test_transformed[1], predict_proba_fn, num_features=5)
exp.show_in_notebook(show_table=True)

print("\nLIME Explanation for X_test instance 2:")
exp = lime_explainer.explain_instance(X_test_transformed[2], predict_proba_fn, num_features=5)
exp.show_in_notebook(show_table=True)



"""### Define New Inputs for Prediction and SHAP Analysis

Please create a Pandas DataFrame `new_inputs_df` with the same columns as `X_test` (`Pclass`, `Sex`, `Age`, `SibSp`, `Parch`, `Fare`, `Embarked`).

**Fill in your desired new inputs here:**
"""

new_inputs_data = {
    'Pclass': [3, 1], # Example: Passenger Class
    'Sex': ['male', 'female'], # Example: Sex
    'Age': [25.0, 45.0], # Example: Age
    'SibSp': [0, 1], # Example: Number of Siblings/Spouses Aboard
    'Parch': [0, 0], # Example: Number of Parents/Children Aboard
    'Fare': [7.25, 71.28], # Example: Fare
    'Embarked': ['S', 'C'] # Example: Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton)
}
new_inputs_df = pd.DataFrame(new_inputs_data)
display(new_inputs_df)

"""### Preprocess New Inputs and Make Predictions"""

# Preprocess the new inputs using the trained preprocessor
new_inputs_transformed = preprocessor.transform(new_inputs_df)

# Make predictions
new_predictions = model.predict(new_inputs_transformed)
print("Predictions for new inputs:", new_predictions)

"""### Generate SHAP Explanations for New Inputs"""

# SHAP Explainer for new inputs
explainer_new = shap.Explainer(model, X_train_transformed, feature_names=feature_names)
shap_values_new = explainer_new(new_inputs_transformed)

# Display individual force plots for each new input
for i in range(len(new_inputs_df)):
    print(f"\nSHAP Force Plot for New Input {i+1} (Prediction: {new_predictions[i]}):")
    shap.plots.force(shap_values_new[i], matplotlib=True)

import joblib

# Define the filename for your model
model_filename = 'titanic_logistic_regression_pipeline.pkl'

# Save the entire pipeline (preprocessor and model) to a .pkl file
joblib.dump(pipe, model_filename)

print(f"Model saved successfully as '{model_filename}'")


# =========================================================================
# FAST SHAP & LIME COMPREHENSIVE EXPLANATIONS (OPTIMIZED APPROACH)
# =========================================================================
print("\n" + "=" * 80)
print("GENERATING COMPREHENSIVE SHAP & LIME EXPLANATIONS")
print("=" * 80)
print("\nKEY OPTIMIZATION:")
print("  - Preprocess data ONCE")
print("  - Explain only the final model (not the full pipeline)")
print("  - Use TreeExplainer for tree models OR LinearExplainer for linear models")
print("  - Avoid KernelExplainer (slow sampling)")
print()

# Try to import SHAP and LIME
try:
    import shap
    import lime
    import lime.lime_tabular
    import matplotlib.pyplot as plt
    EXPLAINERS_AVAILABLE = True
except ImportError as e:
    print(f"[WARNING] SHAP/LIME not available: {e}")
    print("Install with: pip install shap lime matplotlib")
    EXPLAINERS_AVAILABLE = False

if EXPLAINERS_AVAILABLE:
    # ---------------------------------------------------------------------
    # 1. Extract preprocessor and model from pipeline
    # ---------------------------------------------------------------------
    print("\n1. Extracting preprocessor and model from pipeline...")
    preprocessor = pipe.named_steps['preprocessing']
    model = pipe.named_steps['model']
    print(f"   Preprocessor: {type(preprocessor).__name__}")
    print(f"   Model: {type(model).__name__}")

    # ---------------------------------------------------------------------
    # 2. Preprocess training and test data ONCE
    # ---------------------------------------------------------------------
    print("\n2. Preprocessing data (one-time operation)...")
    X_train_transformed = preprocessor.transform(X_train)
    X_test_transformed = preprocessor.transform(X_test)
    print(f"   X_train_transformed: {X_train_transformed.shape}")
    print(f"   X_test_transformed: {X_test_transformed.shape}")

    # ---------------------------------------------------------------------
    # 3. Build feature names list after preprocessing
    # ---------------------------------------------------------------------
    print("\n3. Constructing feature names after one-hot encoding...")

    # Get feature names after preprocessing (simple approach)
    cat_ohe = preprocessor.named_transformers_['cat'].named_steps['onehot']
    cat_feature_names = cat_ohe.get_feature_names_out(categorical_features)
    num_feature_names = numeric_features
    transformed_feature_names = list(cat_feature_names) + list(num_feature_names)

    print(f"   Total transformed features: {len(transformed_feature_names)}")
    print("   First 10 features:")
    for i, name in enumerate(transformed_feature_names[:10], 1):
        print(f"     {i}. {name}")

    # ---------------------------------------------------------------------
    # 4. SHAP EXPLANATIONS (Fast for linear/tree models)
    # ---------------------------------------------------------------------
    print("\n4. Computing SHAP values...")
    print("   Note: For Linear/LogisticRegression, SHAP uses exact analytical solution (very fast).")

    # Create SHAP explainer directly on the model (not the pipeline)
    explainer = shap.Explainer(
        model,
        X_train_transformed,
        feature_names=transformed_feature_names
    )
    shap_values = explainer(X_test_transformed)

    print(f"   [OK] SHAP values computed. Shape: {shap_values.shape}")

    # ---------------------------------------------------------------------
    # 5. SHAP Summary Plot (Global Feature Importance)
    # ---------------------------------------------------------------------
    print("\n5. Creating SHAP summary plot...")
    plt.figure(figsize=(12, 8))
    shap.summary_plot(
        shap_values,
        X_test_transformed,
        feature_names=transformed_feature_names,
        show=False,
        max_display=len(transformed_feature_names),
        plot_size=(12, 8)
    )
    plt.title("SHAP Summary Plot - Global Feature Importance", fontsize=14)
    plt.tight_layout()
    plt.savefig('titanic_shap_summary.png', dpi=150, bbox_inches='tight')
    print("   [OK] Saved: titanic_shap_summary.png")
    plt.close()

    # ---------------------------------------------------------------------
    # 6. SHAP Dependence Plots for Top 3 Features
    # ---------------------------------------------------------------------
    print("\n6. Creating SHAP dependence plots for top 3 features...")
    mean_abs_shap = np.abs(shap_values.values).mean(axis=0)
    top_indices = np.argsort(mean_abs_shap)[-3:][::-1]

    for idx in top_indices:
        feat_name = transformed_feature_names[idx]
        plt.figure(figsize=(10, 6))
        shap.dependence_plot(
            idx,
            shap_values.values,
            X_test_transformed,
            feature_names=transformed_feature_names,
            show=False
        )
        plt.title(f"SHAP Dependence: {feat_name}", fontsize=12)
        plt.tight_layout()
        safe_name = feat_name.replace('/', '_').replace('\\', '_').replace(' ', '_')
        fname = f'titanic_shap_dependence_{safe_name}.png'
        plt.savefig(fname, dpi=150, bbox_inches='tight')
        print(f"   [OK] Saved: {fname}")
        plt.close()

    # ---------------------------------------------------------------------
    # 7. SHAP Force Plot for Sample Prediction (Local Explanation)
    # ---------------------------------------------------------------------
    print("\n7. Creating SHAP force plot for a test sample...")
    sample_idx = 0
    plt.figure(figsize=(20, 4))
    shap.plots.force(
        shap_values[sample_idx],
        matplotlib=True,
        figsize=(20, 4),
        show=False
    )
    plt.title(f"SHAP Force Plot - Test Sample {sample_idx} (True: {y_test.iloc[sample_idx]})", fontsize=12)
    plt.tight_layout()
    plt.savefig('titanic_shap_force_sample0.png', dpi=150, bbox_inches='tight')
    print("   [OK] Saved: titanic_shap_force_sample0.png")
    plt.close()

    # ---------------------------------------------------------------------
    # 8. LIME EXPLANATIONS (Local Interpretable Model-agnostic Explanations)
    # ---------------------------------------------------------------------
    print("\n8. Setting up LIME explainer...")
    lime_explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data=X_train_transformed,
        feature_names=transformed_feature_names,
        class_names=['Died', 'Survived'],
        mode='classification',
        kernel_width=3,
        random_state=42,
        verbose=False
    )
    print("   [OK] LIME explainer initialized")

    # ---------------------------------------------------------------------
    # 9. Generate LIME explanations for test samples
    # ---------------------------------------------------------------------
    print("\n9. Generating LIME explanations for test samples...")

    def predict_proba(X_transformed):
        return model.predict_proba(X_transformed)

    num_lime_samples = min(3, len(X_test))
    for i in range(num_lime_samples):
        exp = lime_explainer.explain_instance(
            X_test_transformed[i],
            predict_proba,
            num_features=10
        )
        html_file = f'titanic_lime_sample{i}.html'
        exp.save_to_file(html_file)
        pred_class = exp.predicted_value.argmax() if len(exp.predicted_value) > 1 else 0
        true_val = y_test.iloc[i]
        print(f"   [OK] Sample {i}: True={true_val}, Predicted class={pred_class}")
        print(f"        Saved: {html_file}")

    # ---------------------------------------------------------------------
    # 10. Feature Importance Comparison: SHAP vs LIME
    # ---------------------------------------------------------------------
    print("\n10. Comparing SHAP and LIME feature importance...")

    # Compute average absolute SHAP importance
    mean_shap_importance = np.abs(shap_values.values).mean(axis=0)

    # Compute average absolute LIME importance across multiple samples
    n_compare = min(20, len(X_test))
    lime_importances = []
    for i in range(n_compare):
        exp = lime_explainer.explain_instance(X_test_transformed[i], predict_proba, num_features=len(transformed_feature_names))
        lime_dict = dict(exp.as_list())
        lime_vals = np.zeros(len(transformed_feature_names))
        for j, feat in enumerate(transformed_feature_names):
            lime_vals[j] = abs(lime_dict.get(feat, 0))
        lime_importances.append(lime_vals)

    mean_lime_importance = np.mean(lime_importances, axis=0)

    # Plot comparison
    top_n = min(15, len(transformed_feature_names))
    top_shap_idx = np.argsort(mean_shap_importance)[-top_n:][::-1]
    top_lime_idx = np.argsort(mean_lime_importance)[-top_n:][::-1]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 10))

    # SHAP top features
    shap_features = [transformed_feature_names[i] for i in top_shap_idx]
    shap_vals = mean_shap_importance[top_shap_idx]
    ax1.barh(range(top_n), shap_vals[::-1])
    ax1.set_yticks(range(top_n))
    ax1.set_yticklabels(shap_features[::-1])
    ax1.set_xlabel('Mean |SHAP value|')
    ax1.set_title('Top Features by SHAP Importance')
    ax1.invert_yaxis()

    # LIME top features
    lime_features = [transformed_feature_names[i] for i in top_lime_idx]
    lime_vals = mean_lime_importance[top_lime_idx]
    ax2.barh(range(top_n), lime_vals[::-1])
    ax2.set_yticks(range(top_n))
    ax2.set_yticklabels(lime_features[::-1])
    ax2.set_xlabel('Mean |LIME weight|')
    ax2.set_title('Top Features by LIME Importance')
    ax2.invert_yaxis()

    plt.suptitle('SHAP vs LIME Feature Importance Comparison', fontsize=14, y=1.02)
    plt.tight_layout()
    plt.savefig('titanic_shap_vs_lime.png', dpi=150, bbox_inches='tight')
    print("   [OK] Saved: titanic_shap_vs_lime.png")
    plt.close()

    # ---------------------------------------------------------------------
    # 11. Summary
    # ---------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("EXPLANATION GENERATION COMPLETE!")
    print("=" * 80)
    print("\nGenerated Files:")
    print("  titanic_shap_summary.png           - Global SHAP feature importance")
    print("  titanic_shap_dependence_*.png      - Dependence plots for top features")
    print("  titanic_shap_force_sample0.png     - Local SHAP explanation")
    print("  titanic_lime_sample*.html          - Interactive LIME explanations")
    print("  titanic_shap_vs_lime.png           - SHAP vs LIME comparison")
    print("\nPerformance Notes:")
    print("  - SHAP for LogisticRegression: exact analytical solution (seconds)")
    print("  - Preprocessing done once, not repeated")
    print("  - LIME uses fast sampling with kernel_width=3")
    print("=" * 80)

else:
    print("\n[Skipped] Install shap, lime, matplotlib to generate explanations:")
    print("  pip install shap lime matplotlib")


